services:
  buddy:
    container_name: buddy
    image: hoangndst/buddy:${BUDDY_VERSION}
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL}
      - SIEU_NHAN_API_BASE=${SIEU_NHAN_API_BASE}
      - FOOTBALL_TOKEN=${FOOTBALL_TOKEN}
    volumes:
      - ./assets:/app/assets
